// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// Opens the index at `path`, creating it if needed. The app passes a file
/// in its own data directory; nothing here guesses where that is.
Future<void> openIndex({required String path}) =>
    RustLib.instance.api.crateApiIndexOpenIndex(path: path);

/// How many screenshots can be searched.
Future<int> shotCount() => RustLib.instance.api.crateApiIndexShotCount();

/// Whether `path` is already indexed as it was at `mtime`.
Future<bool> isCurrent({required String path, required PlatformInt64 mtime}) =>
    RustLib.instance.api.crateApiIndexIsCurrent(path: path, mtime: mtime);

/// `is_current` for a whole page of images at once. Asking one at a time is
/// a trip across the bridge each, and a library is thousands of them.
Future<List<bool>> areCurrent({
  required List<String> paths,
  required Int64List mtimes,
}) =>
    RustLib.instance.api.crateApiIndexAreCurrent(paths: paths, mtimes: mtimes);

/// Stores a screenshot and the lines read from it, replacing whatever was
/// there for the same path. Pass 0 x 0 for an image that could not be read,
/// so it is remembered but never shown.
Future<void> insertShot({
  required String path,
  required PlatformInt64 mtime,
  required int width,
  required int height,
  required List<Line> lines,
}) => RustLib.instance.api.crateApiIndexInsertShot(
  path: path,
  mtime: mtime,
  width: width,
  height: height,
  lines: lines,
);

/// Forgets a screenshot. The file itself is never touched.
Future<bool> removeShot({required String path}) =>
    RustLib.instance.api.crateApiIndexRemoveShot(path: path);

/// Forgets every screenshot, so the next look through the library reads
/// them all again. For after a script is turned on. Only the index is
/// emptied; the files are never touched.
Future<int> forgetAll() => RustLib.instance.api.crateApiIndexForgetAll();

/// Forgets every screenshot whose path is not in `paths`: ones deleted from
/// the phone, and ones in a folder that was turned off. Only the index
/// changes; the files are never touched.
Future<int> keepOnly({required List<String> paths}) =>
    RustLib.instance.api.crateApiIndexKeepOnly(paths: paths);

/// Every word of `query` has to appear in the screenshot; an empty query
/// lists the newest. Filters (`in:`, `date:`) work as on the desktop.
Future<List<Hit>> search({required String query, required int limit}) =>
    RustLib.instance.api.crateApiIndexSearch(query: query, limit: limit);

/// All the text of one screenshot, top to bottom.
Future<List<Line>> shotLines({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiIndexShotLines(id: id);

/// The part of a screenshot its grid tile shows, see `gyotaku_core::tile_crop`.
Rect tileCrop({required int width, required int height}) =>
    RustLib.instance.api.crateApiIndexTileCrop(width: width, height: height);

/// Width over height of a grid tile.
double tileAspect({required int width, required int height}) =>
    RustLib.instance.api.crateApiIndexTileAspect(width: width, height: height);

class Hit {
  final PlatformInt64 id;
  final String path;

  /// Seconds since the epoch.
  final PlatformInt64 mtime;
  final int width;
  final int height;

  /// The lines that contain a query term. Empty without a query.
  final List<Line> lines;

  /// Found only by treating look-alike characters as one (`0` for `O`).
  final bool near;

  const Hit({
    required this.id,
    required this.path,
    required this.mtime,
    required this.width,
    required this.height,
    required this.lines,
    required this.near,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      mtime.hashCode ^
      width.hashCode ^
      height.hashCode ^
      lines.hashCode ^
      near.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Hit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          mtime == other.mtime &&
          width == other.width &&
          height == other.height &&
          lines == other.lines &&
          near == other.near;
}

/// One line of text and where it sits in the screenshot.
class Line {
  final String text;
  final Rect rect;
  final double score;

  const Line({required this.text, required this.rect, required this.score});

  @override
  int get hashCode => text.hashCode ^ rect.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Line &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          rect == other.rect &&
          score == other.score;
}

/// A box in normalized image coordinates, 0 to 1 on both axes.
class Rect {
  final double x;
  final double y;
  final double w;
  final double h;

  const Rect({
    required this.x,
    required this.y,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ w.hashCode ^ h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rect &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          w == other.w &&
          h == other.h;
}
