// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'index.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Tells the core where it lives on this phone. `gyotaku-core` finds its
/// folders the way a Linux program does, from HOME and the XDG variables, and
/// an app has neither until it sets them. `runtime` is the ONNX Runtime
/// library that ships inside the app, for systems where one does.
///
/// Call once, before anything else, while nothing else is running.
void settle({required String home, String? runtime}) =>
    RustLib.instance.api.crateApiReaderSettle(home: home, runtime: runtime);

/// Every script this version knows, and whether it is on.
Future<List<ScriptChoice>> scripts() =>
    RustLib.instance.api.crateApiReaderScripts();

/// Turns a script on or off. Like on the desktop, it applies to screenshots
/// read from then on.
Future<void> setScript({required String name, required bool enabled}) =>
    RustLib.instance.api.crateApiReaderSetScript(name: name, enabled: enabled);

/// Reads one image with the default recognizer and every script that is on.
/// The first call downloads the models it needs, which is the only time this
/// touches the network.
Future<List<Line>> readImage({required String path}) =>
    RustLib.instance.api.crateApiReaderReadImage(path: path);

/// A writing system that can be turned on, see `gyotaku_core::Script`.
class ScriptChoice {
  /// The name in the config, like `bengali`.
  final String name;
  final bool enabled;

  const ScriptChoice({required this.name, required this.enabled});

  @override
  int get hashCode => name.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptChoice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          enabled == other.enabled;
}
